Repository prgrms-fe-devcourse/FEDC5_Yap_YUNHO, pull requests merged in 2023-12, with the labels that each got.

#63 Feature/#62/login user state jae0
  src/Constants/Stores.ts
  src/Stores/authUserStore.ts
Labels: Feat

#66 [UserPage] 유저페이지 - 컴포넌트들 생성 및 페이지에 배치
  src/Pages/Profile/Components/UserAction/FollowButton.tsx
  src/Pages/Profile/Components/UserAction/SendDirectMessageButton.tsx
  src/Pages/Profile/Components/UserAction/UpdateUserInfoButton.tsx
  src/Pages/Profile/Components/UserAction/UserAction.tsx
  src/Pages/Profile/Components/UserFollowInfo.tsx
  src/Pages/Profile/Components/UserNickname.tsx
  src/Pages/Profile/Components/UserPostFilter/UserPostFilter.tsx
  src/Pages/Profile/Components/UserPostFilter/ViewCreatedPostButton.tsx
  src/Pages/Profile/Components/UserPostFilter/ViewLikedPostButton.tsx
  src/Pages/Profile/Components/UserPostList.tsx
  src/Pages/Profile/Components/UserPostListItem.tsx
  src/Pages/Profile/Components/UserProfileImage.tsx
  src/Pages/Profile/Profile.tsx
Labels: Feat

#67 [HomePage] Layout
  src/GlobalStyles.tsx
  src/Pages/Home/Home.Styles.tsx
  src/Pages/Home/Home.tsx
Labels: Feat, Design

#70 [FIX] Mac Windo 호환성 해결 및 폴더 이름 변경 #68
  .eslintrc.cjs
  tsconfig.json
Labels: Fix, Rename

#65 [State] AuthUser-Rename
  src/Stores/useAuthUserStore.ts
Labels: Rename

#73 [HomePage] Category bar 구현
  src/Pages/Home/Home.Styles.tsx
  src/Pages/Home/Home.tsx
  src/Pages/Home/components/CategoryBar/CategoryBar.Styles.ts
  src/Pages/Home/components/CategoryBar/CategoryBar.Types.ts
  src/Pages/Home/components/CategoryBar/CategoryBar.tsx
  src/Stores/useCategoryListStore.ts
Labels: Feat, Design

#72 [Feat ✏️] Navbar 전체 레이아웃 배치
  src/GlobalStyles.tsx
  src/Pages/Home/Home.tsx
  src/assets/logo.png
  src/assets/profile.png
  src/components/Navbar/Navbar.Styles.ts
  src/components/Navbar/Navbar.tsx
Labels: Feat
