Repository prgrms-fe-devcourse/FEDC5_Yap_YUNHO, pull requests merged in 2024-01, with the labels that each got.

#83 [Sprint] 수정 및 추가
  package-lock.json
  package.json
  src/App.tsx
  src/Constants/Stores.ts
  src/Pages/Home/Home.tsx
  src/Pages/Home/components/CategoryBar/CategoryBar.tsx
  src/Routes/index.tsx
  src/Stores/useAuthUserStore.ts
  src/Stores/useCategoryListStore.ts
  src/assets/logo.png
  src/main.tsx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
  tsconfig.json
  vite.config.ts
Labels: Feat, Fix

#84 [Fix] Git - Folder Name
  .gitignore
  src/App.tsx
  src/Constants/ErrorMessage.ts
  src/Pages/Profile/Profile.tsx
  src/Stores/AuthToken.ts
  src/Stores/useAuthUserStore.ts
  src/apis/Api.ts
  src/apis/ApiJWT.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/constants/ErrorMessage.ts
  src/constants/errorMessage.ts
  src/hooks/useLocalStorage.ts
  src/pages/Profile/Profile.tsx
  src/stores/AuthToken.ts
  src/stores/useAuthUserStore.ts
Labels: Fix

#87 [HomePage] Category bar Click Event 구현 및 Filter 구현
  .eslintrc.cjs
  src/apis/ApiJWT.ts
  src/components/Button/Button.Styles.ts
  src/components/Button/Button.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/hooks/useCategoryList.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/CategoryBar/CategoryBar.Styles.ts
  src/pages/Home/components/CategoryBar/CategoryBar.Types.ts
  src/pages/Home/components/CategoryBar/CategoryBar.tsx
  src/stores/useAuthUserStore.ts
  src/stores/useCategoryListStore.ts
Labels: Feat, Design

#81 [Feat ✏️] LoginPage 기본적인 Layout 구현
  src/pages/Login/Login.styles.ts
  src/pages/Login/Login.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat, Design

#89 [PostCard] PostCard Layout 구현
  src/components/PostCard/PostCard.Styles.ts
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.tsx
  src/components/PostCard/components/PostCardThumbnail/PostCardThumbnail.Styles.ts
  src/components/PostCard/components/PostCardThumbnail/PostCardThumbnail.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.Styles.ts
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
Labels: Feat, Design

#94 [MediaPlayer] State
  src/components/MediaPlayer/components/Player.tsx
  src/components/MediaPlayer/constants/mediaPlayer.ts
  src/components/MediaPlayer/hooks/useMediaPlayer.ts
  src/components/MediaPlayer/store/useMediaPlayerStore.Types.ts
  src/components/MediaPlayer/store/useMediaPlayerStore.ts
Labels: Feat

#88 [Design 🎨] 유저 액션 버튼 UI
  src/pages/Profile/components/UserProfile/UserAction/FollowButton.tsx
  src/pages/Profile/components/UserProfile/UserAction/SendDirectMessageButton.tsx
  src/pages/Profile/components/UserProfile/UserAction/UpdateUserInfoButton.tsx
  src/pages/Profile/components/UserProfile/UserAction/UserAction.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserActions.Styles.ts
  src/pages/Profile/components/UserProfile/UserActions/UserActions.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserFollowButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserSendDMButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserUpdateInfoButton.tsx
  src/pages/Profile/components/UserProfile/UserFollowInfo.tsx
  src/pages/Profile/components/UserProfile/UserNickname.tsx
  src/pages/Profile/components/UserProfile/UserProfile.Styles.ts
  src/pages/Profile/components/UserProfile/UserProfile.tsx
  src/pages/Profile/components/UserProfile/UserProfileImage.tsx
  src/pages/Profile/styles/UserProfile.Styles.ts
  src/styles/Profile.Styles.ts
Labels: Design

#93 [LoginPage] Email, Password Inputs 구현
  src/pages/Login/Login.styles.ts
  src/pages/Login/Login.tsx
  src/pages/Login/components/Login/Input/LoginInputContainer.Styles.ts
  src/pages/Login/components/Login/Input/LoginInputContainer.tsx
  src/pages/Login/components/Login/Input/LoginInputItem.Styles.ts
  src/pages/Login/components/Login/Input/LoginInputItem.tsx
  src/pages/Login/components/Login/LoginComponent.Styles.ts
  src/pages/Login/components/Login/LoginComponent.tsx
  src/pages/Login/components/ServiceInfo/ServiceInfoComponent.Styles.ts
  src/pages/Login/components/ServiceInfo/ServiceInfoComponent.tsx
  src/pages/Login/constants/emailValidation.ts
  src/pages/Login/constants/errorMessage.ts
  src/pages/Login/constants/passwordValidation.ts
  src/pages/Login/utils/validation/index.ts
  src/pages/Login/utils/validation/validateEmailInput.ts
  src/pages/Login/utils/validation/validatePasswordInput.ts
  src/pages/Profile/Profile.tsx
  src/routes/index.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat, Design, Refactor

#96 [Feat ✏️] 유저 페이지를 마이페이지와 다른 유저 페이지로 구분
  src/pages/Profile/Profile.Styles.ts
  src/pages/Profile/Profile.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserActions.Styles.ts
  src/pages/Profile/components/UserProfile/UserActions/UserActions.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserFollowButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserSendDMButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserUpdateInfoButton.tsx
  src/pages/Profile/components/UserProfile/UserFollowInfo.tsx
  src/pages/Profile/components/UserProfile/UserProfile.Styles.ts
  src/pages/Profile/components/UserProfile/UserProfile.tsx
Labels: Feat

#103 [Fix 🪛] API 모듈 수정
  src/apis/Api.ts
  src/apis/ApiJWT.ts
Labels: Fix

#97 [PostCard] MediaPlaye 구현
  src/components/MediaPlayer/components/Player.tsx
  src/components/MediaPlayer/constants/mediaPlayer.ts
  src/components/MediaPlayer/hooks/useMediaPlayer.ts
  src/components/PostCard/PostCard.Styles.ts
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/MediaPlayer/MediaPlayer.Styles.ts
  src/components/PostCard/components/MediaPlayer/MediaPlayer.Types.ts
  src/components/PostCard/components/MediaPlayer/MediaPlayer.tsx
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.tsx
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerPlaySlider/MediaPlayerSlider.Styles.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerPlaySlider/MediaPlayerSlider.tsx
  src/components/PostCard/components/MediaPlayer/constants/mediaPlayer.ts
  src/components/PostCard/components/MediaPlayer/hooks/useMediaPlayer.ts
  src/components/PostCard/components/MediaPlayer/hooks/useSlider.ts
  src/components/PostCard/components/MediaPlayer/store/useMediaPlayerStore.Types.ts
  src/components/PostCard/components/MediaPlayer/store/useMediaPlayerStore.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.tsx
  src/components/PostCard/components/PostCardThumbnail/PostCardThumbnail.Styles.ts
  src/components/PostCard/components/PostCardThumbnail/PostCardThumbnail.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.Styles.ts
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/font/BMJUA_otf.otf
  src/font/font.css
  src/pages/Home/components/CategoryBar/CategoryBar.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat, Design, Fix, Refactor

#101 [HomePage] 홈페이지의 전체적 코드 정리
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/MediaPlayer/MediaPlayer.tsx
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.tsx
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerPlaySlider/MediaPlayerSlider.tsx
  src/components/PostCard/components/MediaPlayer/hooks/useMediaPlayer.ts
  src/components/PostCard/components/MediaPlayer/hooks/useSlider.ts
  src/components/PostCard/components/MediaPlayer/store/useMediaPlayerStore.Types.ts
  src/components/PostCard/components/MediaPlayer/store/useMediaPlayerStore.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
Labels: Fix, Refactor

#98 [Navbar] 반응형에 따른 Navbar 디자인/기능 구현
  src/apis/Api.ts
  src/components/Button/Button.Styles.ts
  src/components/Button/Button.tsx
  src/components/Navbar/Navbar.Styles.ts
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.Styles.ts
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.tsx
  src/components/Navbar/components/NavbarRightList/NavbarLoggedInMenu/NavbarLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarMenuItem/NavbarMenuItem.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarMenuItem/NavbarMenuItem.tsx
  src/components/Navbar/components/NavbarRightList/NavbarNotLoggedInMenu/NavbarNotLoggedInMenu.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarNotLoggedInMenu/NavbarNotLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/Navbar/components/NavbarRightList/NavbarToggleMenu/NavbarToggleMenu.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarToggleMenu/NavbarToggleMenu.tsx
  src/components/Navbar/hooks/useNavMenuClick.ts
  src/components/Navbar/types/index.ts
  src/constants/stores.ts
  src/hooks/useToggle.ts
  src/pages/Home/Home.tsx
  src/routes/index.tsx
  src/stores/AuthToken.ts
  src/stores/useAuthUserStore.ts
Labels: Feat, Design

#104 [Modal] 구현
  src/components/Modal/Modal.Styles.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/components/ModalPortal.tsx
  src/components/Modal/hooks/useModal.ts
  src/components/PostCard/components/MediaPlayer/hooks/useSlider.ts
  src/main.Styles.ts
  src/main.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
Labels: Feat

#108 [PostEditModal] layout 구현 및 준비 작업
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.Styles.ts
  src/components/PostEdit/PostEdit.Styles.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.Styles.ts
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.Styles.ts
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/pages/Home/Home.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat, Design

#109 [PostEditModal] Preview 구현
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/PostCardThumbnail/PostCardThumbnail.Styles.ts
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.Styles.ts
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.Styles.ts
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.Styles.ts
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/types/index.ts
Labels: Feat, Design, Refactor

#110 [PostEditModal] Content Input 구현
  src/components/PostEdit/PostEdit.Types.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.Styles.ts
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
Labels: Feat, Design

#112 [PostEdit & Modal ] URL 부분 구현 및 Small Modal 구현
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalGlobal.Styles.ts
  src/components/Modal/components/CustomModal/CustomModal.Styles.ts
  src/components/Modal/components/CustomModal/CustomModal.tsx
  src/components/Modal/components/ModalAlert/ModalAlert.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.tsx
  src/components/Modal/components/ModalConfirm/ModalConfirm.Styles.ts
  src/components/Modal/components/ModalConfirm/ModalConfirm.tsx
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.Styles.ts
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/constants/errorMessage.ts
  src/pages/Home/Home.tsx
  src/styles/theme.ts
Labels: Feat, Design

#114 [DMPage] DM 목록 레이아웃 및 디자인 구현
  src/assets/avatar.png
  src/components/Navbar/components/NavbarRightList/NavbarLoggedInMenu/NavbarLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarNotLoggedInMenu/NavbarNotLoggedInMenu.tsx
  src/pages/DirectMessage/DirectMessage.Styles.ts
  src/pages/DirectMessage/DirectMessage.tsx
  src/pages/DirectMessage/components/DMChattingList/DMChattingList.Styles.ts
  src/pages/DirectMessage/components/DMChattingList/DMChattingList.tsx
  src/pages/DirectMessage/components/DMChattingList/DMChattingList_My.tsx
  src/pages/DirectMessage/components/DMChattingList/DMChattingList_Other.tsx
  src/pages/DirectMessage/components/DMChattingList/DMInput.tsx
  src/pages/DirectMessage/components/DMList/DMList.Styles.ts
  src/pages/DirectMessage/components/DMList/DMList.tsx
  src/pages/DirectMessage/components/DMList/DMListItem.tsx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
Labels: Design

#113 [LoginPage] 로그인 API 연결
  src/pages/Login/Login.styles.ts
  src/pages/Login/Login.tsx
  src/pages/Login/components/Login/Input/LoginInputContainer.Styles.ts
  src/pages/Login/components/Login/Input/LoginInputContainer.tsx
  src/pages/Login/components/Login/Input/LoginInputItem.Styles.ts
  src/pages/Login/components/Login/Input/LoginInputItem.tsx
  src/pages/Login/components/Login/LoginComponent.Styles.ts
  src/pages/Login/components/Login/LoginComponent.tsx
  src/pages/Login/components/Login/types/index.ts
  src/pages/Login/constants/errorMessage.ts
  src/pages/Login/constants/passwordValidation.ts
  src/pages/Login/utils/validation/validatePasswordInput.ts
Labels: Feat

#118 [Login Page] Login Page 반응형으로 디자인
  src/pages/Login/Login.styles.ts
  src/pages/Login/components/Login/Input/LoginInputContainer.Styles.ts
  src/pages/Login/components/Login/Input/LoginInputItem.Styles.ts
  src/pages/Login/components/Login/LoginComponent.Styles.ts
  src/pages/Login/components/ServiceInfo/ServiceInfoComponent.Styles.ts
Labels: Design

#122 [DMPage] DM 목록 기능 구현
  src/assets/seenindicator.png
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/pages/DirectMessage/components/DMChattingList/DMChattingList.Styles.ts
  src/pages/DirectMessage/components/DMChattingList/DMChattingList.tsx
  src/pages/DirectMessage/components/DMList/DMList.Styles.ts
  src/pages/DirectMessage/components/DMList/DMList.tsx
  src/pages/DirectMessage/components/DMList/DMListItem.tsx
  src/pages/DirectMessage/components/DMList/DMListProfile.tsx
  src/pages/DirectMessage/types/index.ts
  src/pages/DirectMessage/utils/decideChatUserName.ts
  src/routes/index.tsx
  src/styles/GlobalStyles.tsx
Labels: Feat

#123 [SearchModal] search 모달 레이아웃 구현
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.tsx
  src/components/Search/Search.Styles.ts
  src/components/Search/Search.tsx
  src/components/Search/components/SearchInput/SearchInput.Styles.ts
  src/components/Search/components/SearchInput/SearchInput.tsx
  src/components/Search/components/SearchInput/components/SearchInputBar/SearchInputBar.Styles.ts
  src/components/Search/components/SearchInput/components/SearchInputBar/SearchInputBar.tsx
  src/components/Search/components/SearchInput/components/SearchInputFilter/SearchInputFilter.Styles.ts
  src/components/Search/components/SearchInput/components/SearchInputFilter/SearchInputFilter.tsx
  src/components/Search/components/SearchResult/SearchResult.Styles.ts
  src/components/Search/components/SearchResult/SearchResult.tsx
  src/components/Search/components/SearchResult/components/SearchResultList.Styles.ts
  src/components/Search/components/SearchResult/components/SearchResultList.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PostContainer/PostContainer.tsx
Labels: Feat, Design

#134 [ Vercel ] 배포 오류 수정
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.tsx
  src/components/PostCard/components/MediaPlayer/constants/MediaPlayer.Constants.ts
  src/components/PostCard/components/MediaPlayer/hooks/useMediaPlayer.ts
  src/components/PostCard/components/MediaPlayer/store/useMediaPlayerStore.ts
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/hooks/useCategoryList.ts
  src/main.tsx
  src/pages/Login/components/Login/Input/LoginInputItem.tsx
  src/pages/Signup/Signup.tsx
  src/pages/UserEdit/UserEdit.tsx
  src/routes/index.tsx
  src/stores/authToken.ts
Labels: Fix

#132 [Feat ✏️] 조건부 라우팅 & persist 도입
  src/components/Navbar/Navbar.tsx
  src/stores/useAuthUserStore.ts
Labels: Fix, Refactor

#137 [Modal] 모달 개선 및 상태관리 변경#136
  src/components/CategoryList/CategoryList.Styles.ts
  src/components/Modal/Modal.Styles.ts
  src/components/Modal/hooks/useModal.ts
  src/components/Modal/store/useModalDepth.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/MediaPlayer/constants/MediaPlayer.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/components/PostEdit/stores/usePostEditModalStore.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/styles/theme.ts
Labels: Feat, Fix, Refactor

#133 [Home] Post 관련 API 구현#131
  src/components/CategoryList/CategoryList.Styles.ts
  src/components/Modal/Modal.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.tsx
  src/components/Modal/hooks/useModal.ts
  src/components/Modal/store/useModalDepth.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/MediaPlayer/constants/MediaPlayer.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditCategory/PostEditCategory.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/components/PostEdit/stores/usePostEditModalStore.ts
  src/hooks/useCategoryList.ts
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Login/components/Login/Input/LoginInputItem.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserFollowButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserSendDMButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserUpdateInfoButton.tsx
  src/pages/Signup/Signup.tsx
  src/pages/UserEdit/UserEdit.tsx
  src/routes/index.tsx
  src/stores/authToken.ts
  src/styles/theme.ts
Labels: Feat, Design, Refactor

#129 [PostEdit] validation, update 구현#128
  src/components/CategoryList/CategoryList.Styles.ts
  src/components/Modal/Modal.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.tsx
  src/components/Modal/hooks/useModal.ts
  src/components/Modal/store/useModalDepth.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/MediaPlayer/constants/MediaPlayer.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostEdit/PostEdit.Types.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/apis/createPost.ts
  src/components/PostEdit/apis/updatePost.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditCategory/PostEditCategory.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditCategory/PostEditCategory.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/components/PostEdit/stores/usePostEditModalStore.ts
  src/components/PostEdit/util/PostCategoryValidation.ts
  src/components/PostEdit/util/PostContentValidation.ts
  src/components/PostEdit/util/PostUrlValidation.ts
  src/components/PostEdit/util/checkCategoryValidation.ts
  src/components/PostEdit/util/checkContentValidation.ts
  src/components/PostEdit/util/checkUrlValidation.ts
  src/constants/errorMessage.ts
  src/hooks/useCategoryList.ts
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/CategoryBar/CategoryBar.Styles.ts
  src/pages/Home/components/CategoryBar/CategoryBar.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Login/components/Login/Input/LoginInputItem.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserFollowButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserSendDMButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserUpdateInfoButton.tsx
  src/pages/Signup/Signup.tsx
  src/pages/UserEdit/UserEdit.tsx
  src/routes/index.tsx
  src/stores/authToken.ts
  src/styles/theme.ts
Labels: Feat, Fix, Refactor

#127 [PostEditModal] Submit 구현#57
  src/components/CategoryList/CategoryList.Styles.ts
  src/components/Modal/Modal.Styles.ts
  src/components/Modal/ModalGlobal.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.Styles.ts
  src/components/Modal/components/ModalAlert/ModalAlert.tsx
  src/components/Modal/hooks/useModal.ts
  src/components/Modal/store/useModalDepth.ts
  src/components/PostCard/components/MediaPlayer/components/MediaPlayerBottom/MediaPlayerBottom.Styles.ts
  src/components/PostCard/components/MediaPlayer/constants/MediaPlayer.ts
  src/components/PostCard/components/PostCardContent/PostCardContent.Styles.ts
  src/components/PostEdit/PostEdit.Types.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/apis/createPost.ts
  src/components/PostEdit/apis/updatePost.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.Styles.ts
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditButton/PostEditButton.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditCategory/PostEditCategory.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditCategory/PostEditCategory.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditInput/PostEditInput.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/components/PostEdit/constants/PostEdit.Constants.ts
  src/components/PostEdit/stores/usePostEditModalStore.ts
  src/components/PostEdit/util/checkCategoryValidation.ts
  src/components/PostEdit/util/checkContentValidation.ts
  src/components/PostEdit/util/checkUrlValidation.ts
  src/constants/errorMessage.ts
  src/hooks/useCategoryList.ts
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/CategoryBar/CategoryBar.Styles.ts
  src/pages/Home/components/CategoryBar/CategoryBar.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Login/components/Login/Input/LoginInputItem.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserFollowButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserSendDMButton.tsx
  src/pages/Profile/components/UserProfile/UserActions/UserUpdateInfoButton.tsx
  src/pages/Signup/Signup.tsx
  src/pages/UserEdit/UserEdit.tsx
  src/routes/index.tsx
  src/stores/authToken.ts
  src/styles/theme.ts
Labels: Feat, Fix

#139 [Refactoring] 1차 전체 코드 정리
  src/apis/Api.ts
  src/components/Button/Button.Styles.ts
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarMenuItem/NavbarMenuItem.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarToggleMenu/NavbarToggleMenu.Styles.ts
  src/hooks/useToggle.ts
  src/pages/DirectMessage/components/DMList/DMList.Styles.ts
  src/pages/Login/components/Login/LoginComponent.Styles.ts
  src/pages/Profile/components/UserPosts/components/UserPostFilter/UserPostFilter.Styles.ts
  src/pages/Profile/components/UserProfile/components/UserActions/UserActions.Styles.ts
  src/pages/Signup/components/SignupForm.Styles.ts
  src/stores/authToken.ts
  src/stores/useAuthUserStore.ts
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
  src/types/index.ts
Labels: Fix, Refactor

#140 [SignupPage] First Signup Form
  src/pages/Login/components/Login/LoginComponent.tsx
  src/pages/Login/components/Login/LoginInput/LoginInputContainer.Styles.ts
  src/pages/Login/components/Login/LoginInput/LoginInputContainer.tsx
  src/pages/Login/components/Login/LoginInput/LoginInputItem.Styles.ts
  src/pages/Login/components/Login/LoginInput/LoginInputItem.tsx
  src/pages/Login/types/index.ts
  src/pages/Signup/Signup.tsx
  src/pages/Signup/components/FirstSignupForm/FirstSignupForm.Styles.ts
  src/pages/Signup/components/FirstSignupForm/FirstSignupForm.tsx
  src/pages/Signup/components/FirstSignupForm/SignupInput/Input.Styles.ts
  src/pages/Signup/components/FirstSignupForm/SignupInput/Input.tsx
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputContainer.Styles.ts
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputContainer.tsx
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputItem.Styles.ts
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputItem.tsx
  src/pages/Signup/types/index.ts
  src/pages/Signup/utils/validateInput.ts
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
Labels: Feat, Design

#149 [SearchModal] search bar 구현
  src/components/Modal/Modal.Styles.ts
  src/components/Search/Search.Constants.ts
  src/components/Search/components/SearchInput/SearchInput.tsx
  src/components/Search/components/SearchInput/components/SearchInputBar/SearchInputBar.Styles.ts
  src/components/Search/components/SearchInput/components/SearchInputBar/SearchInputBar.tsx
  src/components/Search/components/SearchInput/components/SearchInputFilter/SearchInputFilter.Styles.ts
  src/components/Search/components/SearchInput/components/SearchInputFilter/SearchInputFilter.tsx
Labels: Feat, Design

#168 [ PostDetail ] 모든 PR 리뷰 반영
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/components/PostDetailEditActions.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostDetail/hooks/useDeleteComment.tsx
  src/components/PostDetail/hooks/useDeletePost.tsx
  src/components/PostDetail/hooks/useLikePost.tsx
  src/components/PostDetail/hooks/useSendComment.tsx
  src/components/PostDetail/hooks/useUnLikePost.tsx
  src/components/PostDetail/stores/usePostDetailModalStore.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/hooks/useCreatePost.tsx
  src/components/PostEdit/hooks/useUpdatePost.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Home/components/PostContainer/util/getSlicedPostList.ts
Labels: Feat, Fix, Refactor

#166 Feature/#162/follow hook jae0
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/components/PostDetailEditActions.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostDetail/hooks/useDeleteComment.tsx
  src/components/PostDetail/hooks/useDeletePost.tsx
  src/components/PostDetail/hooks/useLikePost.tsx
  src/components/PostDetail/hooks/useSendComment.tsx
  src/components/PostDetail/hooks/useUnLikePost.tsx
  src/components/PostDetail/stores/usePostDetailModalStore.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/hooks/useCreatePost.tsx
  src/components/PostEdit/hooks/useUpdatePost.tsx
  src/constants/errorMessage.ts
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Home/components/PostContainer/util/getSlicedPostList.ts
  src/stores/useAuthUserStore.ts
Labels: Feat, Fix

#159 [PostDetailModal] 1차 리팩토링#157 + #160
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/apis/deleteComment.ts
  src/components/PostDetail/apis/deletePost.ts
  src/components/PostDetail/apis/likePost.ts
  src/components/PostDetail/apis/sendComment.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/PostCommentList.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/components/PostDetailEditActions.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostDetail/hooks/useDeleteComment.tsx
  src/components/PostDetail/hooks/useDeletePost.tsx
  src/components/PostDetail/hooks/useGetPost.tsx
  src/components/PostDetail/hooks/useLikePost.tsx
  src/components/PostDetail/hooks/useSendComment.tsx
  src/components/PostDetail/hooks/useUnLikePost.tsx
  src/components/PostDetail/stores/usePostDetailModalStore.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/apis/createPost.ts
  src/components/PostEdit/apis/updatePost.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/hooks/useCreatePost.tsx
  src/components/PostEdit/hooks/useUpdatePost.tsx
  src/constants/errorMessage.ts
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Home/components/PostContainer/util/getSlicedPostList.ts
  src/stores/useAuthUserStore.ts
Labels: Feat, Fix, Refactor

#156 [PostDetailModal] 댓글 아이템과 리스트 구현#47
  package-lock.json
  package.json
  src/Dummy/PostCommentPrompt/PostCommentPrompt.styles.ts
  src/Dummy/PostCommentPrompt/PostCommentPrompt.tsx
  src/Dummy/hook/useLocalStorage.ts
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/apis/deletePost.ts
  src/components/PostDetail/apis/likePost.ts
  src/components/PostDetail/apis/sendComment.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/PostCommentList.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/PostCommentList.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/components/PostDetailEditActions.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostDetail/hooks/useDeleteComment.tsx
  src/components/PostDetail/hooks/useDeletePost.tsx
  src/components/PostDetail/hooks/useGetPost.tsx
  src/components/PostDetail/hooks/useLikePost.tsx
  src/components/PostDetail/hooks/useSendComment.tsx
  src/components/PostDetail/hooks/useUnLikePost.tsx
  src/components/PostDetail/stores/usePostDetailModalStore.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/apis/createPost.ts
  src/components/PostEdit/apis/updatePost.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/hooks/useCreatePost.tsx
  src/components/PostEdit/hooks/useUpdatePost.tsx
  src/constants/errorMessage.ts
  src/constants/modalMessage.ts
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Home/components/PostContainer/util/getSlicedPostList.ts
  src/stores/useAuthUserStore.ts
  src/types/index.ts
Labels: Feat, Design

#155 [PostDetailModal] Input 구현 및 API 연결#153
  package-lock.json
  package.json
  src/Dummy/PostCommentPrompt/PostCommentPrompt.styles.ts
  src/Dummy/PostCommentPrompt/PostCommentPrompt.tsx
  src/Dummy/hook/useLocalStorage.ts
  src/components/Modal/components/AlertModal/AlertModal.Styles.ts
  src/components/Modal/components/ConfirmModal/ConfirmModal.Styles.ts
  src/components/Modal/components/ModalConfirm/ModalConfirm.Styles.ts
  src/components/Modal/components/ModalConfirm/ModalConfirm.tsx
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/PostDetail.tsx
  src/components/PostDetail/apis/deletePost.ts
  src/components/PostDetail/apis/likePost.ts
  src/components/PostDetail/components/PostDetailInfo/PostDetailInfo.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/PostDetailComment.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/util/commentValidation.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/PostCommentList.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/PostCommentList.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/components/PostDetailEditActions.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostDetail/hooks/useDeleteComment.tsx
  src/components/PostDetail/hooks/useDeletePost.tsx
  src/components/PostDetail/hooks/useGetPost.tsx
  src/components/PostDetail/hooks/useLikePost.tsx
  src/components/PostDetail/hooks/useSendComment.tsx
  src/components/PostDetail/hooks/useUnLikePost.tsx
  src/components/PostDetail/stores/usePostDetailModalStore.ts
  src/components/PostEdit/PostEdit.tsx
  src/components/PostEdit/apis/createPost.ts
  src/components/PostEdit/apis/updatePost.ts
  src/components/PostEdit/components/PostEditAuthChecker.tsx
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.Styles.ts
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/PostEdit/hooks/useCreatePost.tsx
  src/components/PostEdit/hooks/useUpdatePost.tsx
  src/constants/errorMessage.ts
  src/constants/modalMessage.ts
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Home/components/PostContainer/util/getSlicedPostList.ts
  src/stores/useAuthUserStore.ts
  src/types/index.ts
Labels: Feat, Design, Refactor

#170 [Hoxfix] 배포오류 수정 #169
  src/pages/DirectMessage/components/MessageList/MessageItem/OthersMessage/OthersMessage.tsx
  src/pages/DirectMessage/hooks/useChattingList.ts
  src/pages/DirectMessage/hooks/useDMList.ts
  src/pages/DirectMessage/hooks/useSendMessage.ts
Labels: Deploy

#158 [SignupPage] Second Signup Form
  src/assets/emptyimg.png
  src/components/Input/Input.Styles.ts
  src/components/Input/Input.tsx
  src/components/UserProfileImageUpload/UserProfileImageUpload.Styles.ts
  src/components/UserProfileImageUpload/UserProfileImageUpload.tsx
  src/hooks/useLocalStorage.ts
  src/pages/Login/Login.styles.ts
  src/pages/Login/Login.tsx
  src/pages/Login/apis/login.ts
  src/pages/Login/components/Login/LoginComponent.Styles.ts
  src/pages/Login/components/Login/LoginComponent.tsx
  src/pages/Login/components/Login/LoginInput/LoginInputContainer.tsx
  src/pages/Login/components/Login/LoginInput/LoginInputItem.Styles.ts
  src/pages/Login/components/Login/LoginInput/LoginInputItem.tsx
  src/pages/Login/components/ServiceInfo/ServiceInfoComponent.Styles.ts
  src/pages/Login/constants/passwordValidation.ts
  src/pages/Login/hooks/useLogin.tsx
  src/pages/Login/types/index.ts
  src/pages/Login/utils/validation/validateEmailInput.ts
  src/pages/Login/utils/validation/validatePasswordInput.ts
  src/pages/Signup/Signup.Styles.ts
  src/pages/Signup/Signup.tsx
  src/pages/Signup/apis/signup.ts
  src/pages/Signup/apis/signupUploadPhoto.ts
  src/pages/Signup/components/FirstSignupForm/FirstSignupForm.tsx
  src/pages/Signup/components/FirstSignupForm/SignupInput/Input.tsx
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputContainer.Styles.ts
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputContainer.tsx
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputItem.Styles.ts
  src/pages/Signup/components/FirstSignupForm/SignupInput/SignupInputItem.tsx
  src/pages/Signup/components/SignupFirstForm/SignupFirstForm.Styles.ts
  src/pages/Signup/components/SignupFirstForm/SignupFirstForm.tsx
  src/pages/Signup/components/SignupForm.tsx
  src/pages/Signup/components/SignupInput/SignupInputContainer.Styles.ts
  src/pages/Signup/components/SignupInput/SignupInputContainer.tsx
  src/pages/Signup/components/SignupInput/SignupInputItem.Styles.ts
  src/pages/Signup/components/SignupInput/SignupInputItem.tsx
  src/pages/Signup/components/SignupSecondForm/SignupSecondForm.Styles.ts
  src/pages/Signup/components/SignupSecondForm/SignupSecondForm.tsx
  src/pages/Signup/hooks/useSignupFirstForm.tsx
  src/pages/Signup/hooks/useSignupSecondForm.tsx
  src/pages/Signup/types/index.ts
  src/pages/Signup/utils/validateInput.ts
  src/styles/GlobalStyles.tsx
Labels: Feat, Design

#161 [SearchModal] 검색 결과 리스트 구현
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.tsx
  src/components/Search/Search.tsx
  src/components/Search/components/SearchResult/SearchResult.Styles.ts
  src/components/Search/components/SearchResult/SearchResult.tsx
  src/components/Search/components/SearchResult/components/SearchResultList.Styles.ts
  src/components/Search/components/SearchResult/components/SearchResultList.tsx
  src/components/SearchModal/SearchModal.Constants.ts
  src/components/SearchModal/SearchModal.Styles.ts
  src/components/SearchModal/SearchModal.Types.ts
  src/components/SearchModal/SearchModal.tsx
  src/components/SearchModal/components/SearchInput/SearchInput.Styles.ts
  src/components/SearchModal/components/SearchInput/SearchInput.tsx
  src/components/SearchModal/components/SearchInput/components/SearchInputBar/SearchInputBar.Styles.ts
  src/components/SearchModal/components/SearchInput/components/SearchInputBar/SearchInputBar.tsx
  src/components/SearchModal/components/SearchInput/components/SearchInputFilter/SearchInputFilter.Styles.ts
  src/components/SearchModal/components/SearchInput/components/SearchInputFilter/SearchInputFilter.tsx
  src/components/SearchModal/components/SearchResult/SearchResult.Styles.ts
  src/components/SearchModal/components/SearchResult/SearchResult.tsx
  src/components/SearchModal/components/SearchResult/components/SearchResultItem/SearchResultItem.Styles.ts
  src/components/SearchModal/components/SearchResult/components/SearchResultItem/SearchResultItem.tsx
  src/components/SearchModal/components/SearchResult/components/SearchResultItem/components/SearchResultItemTitle.Styles.ts
  src/components/SearchModal/components/SearchResult/components/SearchResultItem/components/SearchResultItemTitle.tsx
  src/components/SearchModal/components/SearchResult/components/SearchResultList.Styles.ts
  src/components/SearchModal/hooks/useSearchResult.ts
  src/components/SearchModal/stores/useSearchModalStore.ts
  src/components/SearchModal/utils/findIndexByLowerCase.ts
  src/pages/DirectMessage/components/MessageGroupList/MessageList.Styles.ts
Labels: Feat, Design

#174 [Navbar] 새로고침 시 store내부 user갱신
  src/components/Navbar/Navbar.tsx
  src/stores/authToken.ts
Labels: Feat

#182 [ComponentLink] 연결작업#181
  src/components/Navbar/components/NavbarRightList/NavbarLoggedInMenu/NavbarLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/Navbar/hooks/useNavMenuClick.tsx
  src/components/Popover/hooks/useHover.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/components/PostDetailEditActions.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailUser/PostDetailUser.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostEdit/PostEdit.tsx
  src/components/UserInfo/UserInfoPopover.tsx
  src/main.tsx
  src/pages/Home/Home.tsx
  vercel.json
Labels: Feat, Refactor

#180 [UserInfoPopover] 내부 기능 연결 #179
  src/apis/sendNotification.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/UserInfoPopover/Components/UserInfoActions/UserInfoActions.Styles.ts
  src/components/UserInfoPopover/Components/UserInfoActions/UserInfoActions.tsx
  src/components/UserInfoPopover/Components/UserInfoNickName/UserInfoNickName.Styles.ts
  src/components/UserInfoPopover/Components/UserInfoNickName/UserInfoNickName.tsx
  src/components/UserInfoPopover/Components/UserInfoProfile/UserInfoProfile.Styles.ts
  src/components/UserInfoPopover/Components/UserInfoProfile/UserInfoProfile.tsx
  src/components/UserInfoPopover/UserInfoPopover.Styles.ts
  src/components/UserInfoPopover/UserInfoPopover.tsx
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/DirectMessage/apis/sendMessageNotificationAPI.ts
  src/pages/DirectMessage/hooks/useSendMessage.tsx
  src/types/index.ts
Labels: Feat, Fix, Refactor

#178 [UserInfoPopover] 내부 디자인 구현#175
  src/Dummy/hook/useLocalStorage.ts
  src/apis/sendNotification.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/components/Popover/Popover.tsx
  src/components/PostCard/PostCard.Types.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/components/PostCardUserProfile/PostCardUserProfile.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentInput/PostCommentInput.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/PostCommentList.Styles.ts
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailComment/components/PostCommentList/components/PostCommentItem.tsx
  src/components/PostDetail/components/PostDetailInfo/components/PostDetailStatus/PostDetailStatus.tsx
  src/components/PostDetail/components/PostDetailViewer/PostDetailViewer.tsx
  src/components/PostEdit/components/PostEditViewer/PostEditViewer.tsx
  src/components/UserInfoPopover/Components/UserInfoActions/UserInfoActions.Styles.ts
  src/components/UserInfoPopover/Components/UserInfoActions/UserInfoActions.tsx
  src/components/UserInfoPopover/Components/UserInfoFollowStatus/UserInfoFollowStatus.Styles.ts
  src/components/UserInfoPopover/Components/UserInfoFollowStatus/UserInfoFollowStatus.tsx
  src/components/UserInfoPopover/Components/UserInfoProfile/UserInfoProfile.Styles.ts
  src/components/UserInfoPopover/Components/UserInfoProfile/UserInfoProfile.tsx
  src/components/UserInfoPopover/UserInfoPopover.Styles.ts
  src/components/UserInfoPopover/UserInfoPopover.tsx
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/DirectMessage/apis/sendMessageNotificationAPI.ts
  src/pages/DirectMessage/hooks/useSendMessage.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Profile/components/UserProfile/UserProfile.tsx
  src/types/index.ts
Labels: Feat, Design

#187 Feature/#184/404 page jae0
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/NotFound404/NotFound404.Styles.ts
  src/pages/NotFound404/NotFound404.tsx
  src/pages/index.tsx
  src/routes/index.tsx
  src/styles/theme.ts
Labels: Feat, Design

#189 [Feat ✏️] 로고 애니메이션 추가
  src/components/Navbar/Navbar.Styles.ts
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarToggleMenu/NavbarToggleMenu.Styles.ts
  src/pages/DirectMessage/components/MessageGroupList/MessageList.Styles.ts
  src/pages/DirectMessage/components/MessageList/MessageList.Styles.ts
Labels: Refactor

#183 [Notification] 알림 레이아웃 및 기능 구현
  src/components/Button/Button.Styles.ts
  src/components/Modal/components/CustomModal/CustomModal.Styles.ts
  src/components/Modal/hooks/useModal.ts
  src/components/Navbar/Navbar.Types.ts
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarLoggedInMenu/NavbarLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarMenuItem/NavbarMenuItem.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarMenuItem/NavbarMenuItem.tsx
  src/components/Navbar/components/NavbarRightList/NavbarNotLoggedInMenu/NavbarNotLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/Navbar/hooks/useNavMenuClick.tsx
  src/components/NotificationModal/NotificationModal.Styles.ts
  src/components/NotificationModal/NotificationModal.tsx
  src/components/NotificationModal/apis/getNotificationAPI.ts
  src/components/NotificationModal/apis/seenNotificationAPI.ts
  src/components/NotificationModal/components/Notification.Styles.ts
  src/components/NotificationModal/components/NotificationItem.tsx
  src/components/NotificationModal/components/NotificationList.tsx
  src/components/NotificationModal/components/NotificationTitle.tsx
  src/components/NotificationModal/hooks/useGetNotification.ts
  src/components/NotificationModal/hooks/useSeenNotification.ts
  src/components/NotificationModal/utils/getNotificationOption.ts
  src/components/PostDetail/hooks/useGetPost.tsx
  src/pages/DirectMessage/DirectMessage.Styles.ts
  src/pages/DirectMessage/DirectMessage.Types.ts
  src/pages/DirectMessage/DirectMessage.tsx
  src/pages/DirectMessage/apis/getMessageGroupListAPI.ts
  src/pages/DirectMessage/apis/getMessageListAPI.ts
  src/pages/DirectMessage/apis/sendMessageAPI.ts
  src/pages/DirectMessage/components/MessageGroupList/MessageGroupItem.tsx
  src/pages/DirectMessage/components/MessageGroupList/MessageGroupList.Styles.ts
  src/pages/DirectMessage/components/MessageGroupList/MessageGroupList.tsx
  src/pages/DirectMessage/components/MessageGroupList/MessageProfile.tsx
  src/pages/DirectMessage/components/MessageList/MessageInput/MessageInput.tsx
  src/pages/DirectMessage/components/MessageList/MessageItem/MessageItem.tsx
  src/pages/DirectMessage/components/MessageList/MessageList.tsx
  src/pages/DirectMessage/hooks/useMessageGroupList.ts
  src/pages/DirectMessage/hooks/useMessageList.ts
  src/pages/DirectMessage/hooks/useSendMessage.tsx
  src/pages/Profile/components/UserProfile/components/UserActions/UserActions.tsx
  src/routes/index.tsx
  src/stores/authToken.ts
  src/stores/useAuthUserStore.ts
  src/types/index.ts
Labels: Feat, Design

#193 Fix/#3/deploy jae0
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.Styles.ts
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/Navbar/hooks/useNavMenuClick.tsx
  src/components/NotificationModal/apis/getNotificationAPI.ts
  src/components/NotificationModal/apis/seenNotificationAPI.ts
  src/components/NotificationModal/hooks/useGetNotification.ts
  src/components/NotificationModal/hooks/useSeenNotification.ts
  src/components/NotificationModal/utils/getNotificationOption.ts
  src/components/PostCard/components/MediaPlayer/MediaPlayer.tsx
  src/components/PostDetail/hooks/useGetPost.tsx
  src/components/PostDetail/hooks/useLikePost.tsx
  src/components/PostDetail/hooks/useUnLikePost.tsx
  src/components/UserInfoPopover/Components/UserInfoProfile/UserInfoProfile.tsx
  src/hooks/useFetchFollow.tsx
  src/hooks/useFetchUnFollow.tsx
  src/pages/DirectMessage/DirectMessage.tsx
  src/pages/DirectMessage/apis/getMessageGroupListAPI.ts
  src/pages/DirectMessage/hooks/useMessageGroupList.ts
  src/pages/DirectMessage/hooks/useMessageList.ts
  src/pages/DirectMessage/hooks/useSendMessage.tsx
  src/pages/Home/components/PostContainer/PostContainer.Styles.ts
  src/pages/Home/components/PostContainer/PostContainer.tsx
  src/pages/Home/components/PostContainer/components/PostCardList.Styles.ts
  src/pages/Home/components/PostContainer/components/PostCardList.tsx
  src/pages/Profile/Profile.Styles.ts
  src/pages/Profile/components/UserPosts/UserPosts.tsx
  src/pages/Profile/components/UserPosts/components/UserPostFilter/UserPostFilter.Styles.ts
  src/pages/Profile/components/UserPosts/components/UserPostList/UserCreatePostList.tsx
  src/pages/Profile/components/UserPosts/hooks/useCreatePostList.ts
  src/pages/Profile/components/UserProfile/UserProfile.Styles.ts
  src/pages/Profile/components/UserProfile/components/UserActions/UserActions.Styles.ts
  src/routes/index.tsx
  src/stores/authToken.ts
Labels: Fix, Refactor

#196 [Message] 메세지 멘트 수정#195
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/NotificationModal/hooks/useSeenNotification.ts
  src/components/PostEdit/components/PostEditEditor/PostEditEditor.tsx
  src/constants/errorMessage.ts
  src/constants/modalMessage.ts
  src/constants/placeholderMessage.ts
  src/pages/DirectMessage/apis/sendMessageAPI.ts
  src/pages/DirectMessage/components/MessageList/MessageInput/MessageInput.tsx
  src/pages/DirectMessage/hooks/useSendMessage.tsx
  src/pages/Login/constants/errorMessage.ts
  src/pages/Login/hooks/useLogin.tsx
  src/pages/Login/utils/validation/validateEmailInput.ts
  src/pages/Profile/components/UserProfile/UserProfile.tsx
  src/pages/Signup/components/SignupInput/SignupInputContainer.tsx
  src/pages/Signup/hooks/useSignupFirstForm.tsx
  src/pages/Signup/hooks/useSignupSecondForm.tsx
  src/pages/Signup/utils/validateInput.ts
  src/pages/UserEdit/components/UserEditInput/UserEditInputContainer.tsx
  src/pages/UserEdit/hooks/useEditNickname.tsx
  src/pages/UserEdit/hooks/useEditPassword.tsx
  src/pages/UserEdit/hooks/useEditUserProfileImage.tsx
  src/pages/UserEdit/utils/validateInput.ts
Labels: Refactor

#197 [Refactor] 불필요한 파일 삭제
  src/components/Navbar/Navbar.Types.ts
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.tsx
  src/components/Navbar/components/NavbarRightList/NavbarLoggedInMenu/NavbarLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarMenuItem/NavbarMenuItem.tsx
  src/components/Navbar/components/NavbarRightList/NavbarNotLoggedInMenu/NavbarNotLoggedInMenu.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/Navbar/hooks/useNavMenuClick.tsx
  src/components/UserInfoPopover/Components/UserInfoProfile/UserInfoProfile.Styles.ts
  src/pages/DirectMessage/components/MessageGroupList/MessageGroupItem.tsx
  src/pages/DirectMessage/components/MessageGroupList/MessageGroupList.Styles.ts
  src/pages/DirectMessage/components/MessageGroupList/MessageGroupRightInfo.tsx
Labels: Refactor

#198 [Refactor] Button-Jonguk
  src/Dummy/PostCommentPrompt/PostCommentPrompt.tsx
  src/components/Modal/components/AlertModal/AlertModal.tsx
  src/components/Modal/components/ConfirmModal/ConfirmModal.tsx
  src/components/Navbar/Navbar.Styles.ts
  src/components/Navbar/components/NavbarLeftList/NavbarLeftList.tsx
  src/components/Navbar/components/NavbarRightList/NavbarRightList.tsx
  src/components/NotificationModal/components/NotificationTitle.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/PostEditUrl.tsx
  src/components/PostEdit/components/PostEditEditor/components/PostEditUrl/components/PostEditUrlPrompt.tsx
  src/components/ProfileImageUpload/ProfileImageUpload.tsx
  src/components/UserInfoPopover/Components/UserInfoActions/UserInfoActions.tsx
  src/pages/Home/Home.Styles.ts
  src/pages/Login/components/Login/LoginComponent.tsx
  src/pages/NotFound404/NotFound404.tsx
  src/pages/Profile/components/UserPosts/components/UserPostFilter/UserPostFilter.tsx
  src/pages/Profile/components/UserProfile/components/UserActions/UserFollowActionButton.tsx
  src/pages/Signup/components/SignupFirstForm/SignupFirstForm.tsx
  src/pages/Signup/components/SignupSecondForm/SignupSecondForm.tsx
  src/pages/Signup/hooks/useSignupSecondForm.tsx
  src/pages/UserEdit/components/UserEditForm.tsx
Labels: Refactor

#202 README 수정 V1
  README.md
  src/constants/placeholderMessage.ts
Labels: Docs

#200 [Home] 카테고리 항목 랜덤 선택
  src/hooks/useCategoryList.ts
  src/pages/Home/Home.tsx
  src/pages/Home/util/getRandomCategory.ts
Labels: Feat, Fix, Refactor

#203 [HotFix] 재로그인시 이전 사용자 값 불러오는 문제 해결(DM, 알림)
  src/components/Navbar/hooks/useNavMenuClick.tsx
  src/hooks/useLogout.ts
Labels: Fix

#204 README 수정
  README.md
Labels: Docs
